name: Docker update
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: ${{ github.repository }}
         tag_with_ref: true
         tag_with_sha: true
         tags: latest
         repository: ${{ secrets.DOCKER_USERNAME }}/recetas-iv
         tags: latest
