name: Sincronizacion README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sincronizacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Sync
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: <dockerhub username>
          password: <dockerhub password>
          repository: <dockerhub name/repo>
          readme: "./README.md"
