name: Sincronizacion README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sincronizacion:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - uses: meeDamian/sync-readme@v1.0.6
      with:
        pass: ${{ secrets.DOCKER_PASS }}
        description: true
